image: gitpod/workspace-base

tasks:
- name: install gfastats
  command: |
    cd /workspace
    #gfastats
    wget https://github.com/vgl-hub/gfastats/releases/download/v1.3.8/gfastats.v1.3.8-linux.zip
    unzip gfastats.v1.3.8-linux.zip
    chmod a+x ./gfastats
    #rdeval
    wget https://github.com/vgl-hub/rdeval/releases/download/v0.0.2/rdeval.v0.0.2-linux.zip
    unzip rdeval.v0.0.2-linux.zip
    chmod a+x ./rdeval
    #kreeq
    wget https://github.com/vgl-hub/kreeq/releases/download/v0.0.1/kreeq.v0.0.1-linux.zip
    unzip kreeq.v0.0.1-linux.zip
    chmod a+x ./kreeq
    export PATH=/workspace:$PATH
    #teloscope
    wget https://github.com/vgl-hub/teloscope/releases/download/v0.0.1/teloscope.v0.0.1-linux.zip
    unzip teloscope.v0.0.1-linux.zip
    chmod a+x ./teloscope
    #large data
    wget https://genomeark.s3.amazonaws.com/trainingmaterials/BGA2023/large_input.fasta.gz
    wget https://genomeark.s3.amazonaws.com/trainingmaterials/BGA2023/filtered.fastq
    wget https://genomeark.s3.amazonaws.com/trainingmaterials/BGA2023/filtered2.fastq
    wget https://genomeark.s3.amazonaws.com/trainingmaterials/BGA2023/input.fa
    wget https://s3.amazonaws.com/genomeark/species/Gorilla_gorilla/mGorGor1/assembly_curated/mGorGor1.pat.cur.20231122.fasta.gz
    wget https://s3.amazonaws.com/genomeark/species/Pan_paniscus/mPanPan1/assembly_curated/mPanPan1.mat.cur.20231122.fasta.gz
    wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/985/GCF_000002985.6_WBcel235/GCF_000002985.6_WBcel235_genomic.fna.gz
workspaceLocation: "/workspace"
